### PR TITLE
Edit source(src) at the image popover.

### PR DESCRIPTION
**Pull request by yumewang**

### CODE REVIEW

**Comment by ghost** [comment]
There's conflicts that need to be fixed before the PR can be merged. Once I have time I can go through your changes and see what's going on, and integrate the changes you've made in the PR, and see how it goes.
Or would you rather having a go at fixing it?

**Comment by yumewang** [comment]
@StudioJunkyard I have just fixed conflicts. Please check it. If there are any others questions, please feel free to tell me.

**Comment by ghost** [comment]
Looks good, but we should maybe have a help box indicating that select an image will replace any server based image with an inline image. Otherwise people may expect the image to be uploaded to the hosting service, not embedded inline.
I can add that if you don't want.

**Comment by ghost** [comment]
ok, just found an issue. If there's an image already present, and it gets changed so the new image is embedded, when saved, the data in the editor is wiped. So if you refresh to see if the content change worked, it comes back empty. I'll check here a little farther, as it could be my end.

**Comment by yumewang** [comment]
About having a help box, I don't know how to show it, or where do I show it more better. Can you give me some recommendations.

**Comment by yumewang** [comment]
@StudioJunkyard Can you give me some details to find this problem: the content becomes empty. I have just checked it in my project, It can works, just replace the image already present whatever it saved or saved and refreshed. 

If you are doing this, just ignore me, and go ahead. If there are any results, please tell me when you are free.

**Comment by ghost** [comment]
lol, I just did do this, just need to add the changes

**Comment by ghost** [comment]
I'll check again with the content issue, I just made the changes for the help box, and added the different languages for it.

**Comment by ghost** [comment]
OK, I found the issue, I think. On my backend when content is saved, inline images are stripped out, which I do to discourage client's from embedding images, as it significantly increases page load speed, which as you know is bad for SEO.
So, I'll make an option that defaults to false, which disabled the ability to select new images, but leaves the source input alone, that way images used from a different source can still be used.

**Comment by yumewang** [comment]
@StudioJunkyard I saw what you changes about a help box. GOOD.
And about the content becomes empty, maybe you can keep the ability to select new images, and add callbacks.onImageUpload to handle images to the hosting service, not embedded inline.

**Comment by ghost** [comment]
I'll have a think about it, just about to have dinner, lol.

**Comment by yumewang** [comment]
I have a little confused format of JS code. Our project use [Vue](http://rc.vuejs.org/), [vue-cli](https://github.com/vuejs/vue-cli), and use Eslint to check code. There are some [standard JavaScript rules](https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style) which we need to keep, but there did not do this. So when I import it, I need to comment Eslint configure. Errors like below:
error
I know It's my problem, but I have no good ways to handle this.
Maybe we can format JS code?
Enjoy your dinner, and good night.

**Comment by ghost** [comment]
Yeah, that's more than likely my fault. I tend to remove unnecessary spaces. Obviously, linters don't like that, and I don't use them.

**Comment by yumewang** [comment]
I got what you said. Thank you.

**Pull request merged**
