### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by sogoagain**
Your good plugin helped me a lot.
I add a Korean translation so that more people can use this plugin.
Thank you.

### CODE REVIEW

**Comment by DennisSuitters** [comment]
Thanks for your contribution, and apologies for the time it took for me to realise it.

**Comment by sogoagain** [comment]
> Thanks for your contribution, and apologies for the time it took for me to realise it.

Thank you!!

**Comment by DennisSuitters** [comment]
I'm currently waiting for a PR to the main project (I'm able to merge it myself, but I think it's rude to do without the go-ahead as it's not my project), so I can make some major changes to all my plugins.

**Comment by sogoagain** [comment]
> I'm currently waiting for a PR to the main project (I'm able to merge it myself, but I think it's rude to do without the go-ahead as it's not my project), so I can make some major changes to all my plugins.

I'm a bit confused. Do you mean the main project is summernote project? Is there anything else I need to do?

Thank you. :)

**Comment by DennisSuitters** [comment]
Your good to go, yes I mean to the main Summernote project, just letting you know as this plugin will be updated soon and may break with older versions of Summernote.

**Comment by sogoagain** [comment]
> Your good to go, yes I mean to the main Summernote project, just letting you know as this plugin will be updated soon and may break with older versions of Summernote.

Wow! Congratulations. Looking forward to the new version. Thank you.

**Pull request merged**
