### PR TITLE
Spanish + other small improvements

### PR DESCRIPTION
**Pull request by MarcosBL**
Added Spanish support
Bootstrap Classes selector now ensure no duplicates & remove extra spaces
Form labels now act as... you know, labels (clickable to focus field)
Default icon update to latest Summernote

### CODE REVIEW

**Comment by ghost** [comment]
Nice work, as you could see I was too lazy to make a proper onchange event for adding classes, lol. I like your solution, nice, and elegant.

**Comment by MarcosBL** [comment]
Every big opportunity starts with a little conversation. I only took the time for this because you started it :)

I'm going to send nother another PR with my take into Shapes implementation + a couple bugfixes

**Comment by ghost** [comment]
So true, and why I love Open Source.

**Comment by MarcosBL** [comment]
PR sent as https://github.com/StudioJunkyard/summernote-image-attributes/pull/4

**General changes:**
- Optionally adds a dropdown to choose from Bootstrap image shapes (imageShape plugin alias)
- Fixed fields with name attributes creating unwanted extra form fields being posted when dialogsInBody:false
- Fixed typo that was storing a "ref" attribute instead of the correct "rel" ( f / l )
- Now First field is focused (and it's content selected) on popup opening, so you can use the keyboard to tab-fill all form fields

**Related to new feature "Image shapes":**
- Moved image shapes as an option, so it can be extended easily
- Now both bar dropdown & popup dropdown selector uses the same shapes collection
- Now everything respect language (even dropdown empty option + shapes)
- Shapes are now mutually exclusive in the popup too

If you decide to merge it, it would be nice to update your repo screenshots as well ( I just kept your old ones linked in mine )

**Pull request merged**
