### PR TITLE
added german translation; Changed attributes modal window layout

### PR DESCRIPTION
**Pull request by YaWK**
Added german translation. Changed layout of the attributes modal window to horizontal description, because the current branch breaks up the view on my desktop @ google chrome 53. Maybe this is also useful for anyone else.

### CODE REVIEW

**Comment by ghost** [comment]
Hi @YaWK, I appreciate your efforts with this PR. However, where does the styling come from for the Horizontal layout. `dl-horizontal`, isn't something that I'm aware that Bootstrap has, wouldn't adding that break the layout for others using the plugin?

**Comment by YaWK** [comment]
Hi! @StudioJunkyard!
This is Bootstrap 3. See here: http://getbootstrap.com/css/#horizontal-description 
I made the style changes, because I needed them. Feel free to just take the german translation, if you want to. 
Cheers!

**Comment by ghost** [comment]
Pays to read, I'd never even noticed it before, oh well. I'll pull out and add the translation, and have a look at your other changes and see if they make things work better, and if so, add those as well.

**Comment by ghost** [comment]
Actually, we might even be able to make horizontal layout an option that can be toggled.

**Comment by ghost** [comment]
Ok, I've added your German translation, and added a couple more. I also tidied up the Horizontal layout a bit, mainly the code layout, and added for and id attributes so they don't clash with other page elements.

**Pull request closed without merging**
