### PR TITLE
ImageShape plugin, form focus, extra fields fix, rel attribute fix

### PR DESCRIPTION
**Pull request by MarcosBL**
General changes:
- Optionally adds a dropdown to choose from Bootstrap image shapes (imageShape plugin alias)
- Fixed fields with name attributes creating unwanted extra form fields being posted when dialogsInBody:false
- Fixed typo that was storing a "ref" attribute instead of the correct "rel" ( f / l )
- Now First field is focused (and it's content selected) on popup opening, so you can use the keyboard to tab-fill all form fields

Related to new feature "Image shapes":
- Moved image shapes as an option, so it can be extended easily
- Now both bar dropdown & popup dropdown selector uses the same shapes collection
- Now everything respect language (even dropdown empty option + shapes)
- Shapes are now mutually exclusive in the popup too

### CODE REVIEW

**Comment by ghost** [comment]
Geez, you've been busy, nice work on this. I've been out cutting firewood while you did this, haha.

**Comment by MarcosBL** [comment]
It was 4 AM - 6 AM here, the hours when my 2 years old baby girl let me code instead of watching Peppa Pig cartoons !

It would be nice if you can update your repo screenshots as well, when you finish with the firewood of course :+1:

**Comment by ghost** [comment]
Will do the screenshots, 3:15PM here atm, my two monkeys (7 and 9) are in the middle of watching the 2nd Pirates of the Carribbean (most likely spelt wrong, lol). I too usually take the opportunity when they're at school, or gone to be. Such is a parent/coder's life, lol.

**Comment by MarcosBL** [comment]
I'm pretty sure Nature make them cute as hell so we don't just eat them and go ahead with our lives

**Comment by ghost** [comment]
lol.

I'm getting some issue's here. There must be a typo or something in the script, as my SN doesn't render properly, leaving the textarea visible at the top. The buttons appear in the popover, and the dropdown is displayed, but clicking the edit, doesn't open the modal, and the select forces the page to change. (Probably something I've done. I'm more of a PHP coder than JS :D )
screenshot from 2016-05-22 15 25 15

**Comment by ghost** [comment]
hm, ok, if I don't put in the options when initialising Summernote, the behaviour works as expected, except when selecting an image shape, which it does add, but then wants to redirect the page, so may need to add a preventDefault somewhere.

**Comment by ghost** [comment]
Added a preventDefault, now just need to work out why when using the options that it stops working.

**Comment by ghost** [comment]
The plugin stops working correctly when the

``` javascript
imageShape: {
   icon: '<i class="note-icon-picture"/>'
}
```

options are used. But everything is fine if the option isn't explicitly set when calling SN.

**Comment by MarcosBL** [comment]
I'm trying to reproduce in local, was you able to solve the other problems? is it now reduced to this?

**Comment by MarcosBL** [comment]
Ok, I see (think so) what the problem is: as options are arrays, everything works if you pass ALL the options, but fails if you only pass one. It seems it doesn't merge the options, but overwrite them, making the plugin fail, any idea on that ? I just copied over your initial options system

**Comment by ghost** [comment]
I'm not sure how they're doing that with the options, I've never noticed these type of failure's before.

**Comment by MarcosBL** [comment]
Something weird: I see you added a comma as a typo, but that comma is in my file: https://github.com/MarcosBL/summernote-image-attributes/blob/master/summernote-image-attributes.js#L78

And if you look at your commit https://github.com/StudioJunkyard/summernote-image-attributes/commit/167e3af7a644c6a0c73e057e63660001b07fa525  you'll see a lot of changes more over my code

Maybe something broke in the merge?

**Comment by MarcosBL** [comment]
Ok, please ensure we work over the same code, doing a commit with this code https://github.com/MarcosBL/summernote-image-attributes/blob/master/summernote-image-attributes.js and I'll try to find a solution for the options :+1:

**Comment by ghost** [comment]
No worries, I'll leave it as be. I'm working on something else atm anyway.

**Comment by MarcosBL** [comment]
Ok, I know what happens. For the options to be able to be override, you'll need something like:

```
imageAttributes-icon: '<i class="note-icon-pencil"/>',
imageAttributes-removeEmpty:true
```

instead of 

```
imageAttributes: {
    icon: '<i class="note-icon-pencil"/>',
    removeEmpty:true
},
```

As the current notation overwrites the whole **imageAttributes** object with the defined one. So with the current notation is either defining all fields or none (the same as with Summernote buttons definition btw). As there are only a couple of settings, I think a note in the README should be enought for that.

As per your problem, it's a mess with the latest commits, I tested local both Chrome/Firefox and Mint/Windows, and everything is working as expected, so now the project in it's current status is broken; if you can, just roll back your latest changes, or copy&paste my file and do a new commit to fix it. 

Then you can test with no settings in local, and with all settings, and both should work fine.

**Comment by ghost** [comment]
Now here's a silly question, "How do I Roll Back Commits?", it's not something I've had to do before, and I can't see where to do such a thing.

**Comment by MarcosBL** [comment]
There is a way http://stackoverflow.com/questions/4114095/revert-git-repo-to-a-previous-commit

But with such a small project like this, it is by far easier to just copy the whole file from https://github.com/MarcosBL/summernote-image-attributes/blob/master/summernote-image-attributes.js , paste over yours, and do yourself a new commit, so it overwrites the changes, and everything ends fixed x)

**Comment by ghost** [comment]
Ok, done the copy/paste to do the revert. I haven't cloned the repo to my local machine, so doing the console commands weren't an option, hence why I was looking for a way to do it through the web interface, lol.

I had added `event.preventDefault();` at line 366, directly below the on click event.

**Comment by MarcosBL** [comment]
Fine, no problem. What is the `event.preventDefault()` for? That code is in the dropdown selector, which have no action on any button, in fact there is no "Default" action to prevent.

What happens in your installation if you don't add the `event.preventDefault()` ?

**Comment by ghost** [comment]
if I don't add it, changing the selection in the dropdown changes the page. I think it's because SN is within a Form.

**Comment by MarcosBL** [comment]
Don't think so... I use it inside a form, just replacing a textarea, and it doesn't do that.

Are you sure there is nothing more attached to your click events? Could you setup a minimal HTML page to test?

**Comment by ghost** [comment]
I might do that, I think I might know what could be doing it, I have an event listener attached to the page for when input's are changed to update fields, Might have to refine that a bit so it only targets certain fields.

**Pull request merged**
