### PR TITLE
Change image src if modified

### PR DESCRIPTION
**Pull request by pmosse**

### CODE REVIEW

**Comment by DennisSuitters** [comment]
Line 199 `if(imgInfo.src)$img.attr('src',imgInfo.src);else$img.attr('src', '#');` should be setting the image src. Was this not the case for you?

**Comment by DennisSuitters** [comment]
This PR actually would conflict now, as I've gone through a lot of the code to check for errors. I've also added Travis to the repo. Let me know if the problem persists and I'll manually add your changes, or you can close this PR and create a new one with the changes you want to make.

**Comment by pmosse** [comment]
Hey @DiemenDesign, it was not working for me previously but now with the last version it is working fine, so we could close this PR. Thank you!

**Comment by DennisSuitters** [comment]
No worries, glad it was resolved for you. Your PR did give clues to the issue.

**Pull request closed without merging**
